# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.IntegerField(max_length=255)),
                ('cast_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(max_length=255)),
                ('director_id', models.IntegerField(max_length=255)),
                ('cast_id', models.IntegerField(max_length=255)),
                ('genre_id', models.IntegerField(max_length=255)),
                ('type_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.IntegerField(max_length=255)),
                ('director_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(max_length=255)),
                ('genre_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(max_length=255)),
                ('payment_date', models.DateTimeField(max_length=255)),
                ('plan_id', models.IntegerField(max_length=255)),
                ('user_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(max_length=255)),
                ('plan_desc', models.CharField(max_length=255)),
                ('plan_price', models.IntegerField(max_length=255)),
                ('user_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_id', models.IntegerField(max_length=255)),
                ('user_id', models.IntegerField(max_length=255)),
                ('content_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.IntegerField(max_length=255)),
                ('stream_date', models.DateTimeField(max_length=255)),
                ('stream_length', models.IntegerField(max_length=255)),
                ('content_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(max_length=255)),
                ('type_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('zip_id', models.IntegerField()),
                ('user_country', models.CharField(max_length=255)),
                ('user_phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rental_id', models.IntegerField(max_length=255)),
                ('user_id', models.IntegerField(max_length=255)),
                ('rental_id', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_id', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
