# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_auto_20171009_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='audio_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='subtitle_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='video_quality',
            field=models.IntegerField(default=0),
        ),
    ]
