# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_auto_20171010_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
